### ISSUE TITLE
Reference Bug

### ISSUE THREAD

**Issue by vu-luong** [mrtrunghieu1/Imputation_Surveys#1]
`X_data` still refers to `data`. When we execute `X_data[i][j] = np.NaN`, the corresponding value in `data` will change as well. Please fix this bug and be careful with referencing issues in python!

https://github.com/mrtrunghieu1/Imputation_Surveys/blob/3c1dd8c8090ae404838424cc802ab5519a3138d8/data_processing.py#L30-L49

**Comment by mrtrunghieu1** [comment]
I just finished fixing the code, next time I will notice this error!
