### ISSUE TITLE
Hard-code problems

### ISSUE THREAD

**Issue by vu-luong** [mrtrunghieu1/Imputation_Surveys#2]
The number of iterations and folds should be hyper-parameters. The number `fold_size` can be deduced from these parameters as well. We should not hard code them!

https://github.com/mrtrunghieu1/Imputation_Surveys/blob/3c1dd8c8090ae404838424cc802ab5519a3138d8/demo_data_imputation.py#L41

https://github.com/mrtrunghieu1/Imputation_Surveys/blob/3c1dd8c8090ae404838424cc802ab5519a3138d8/demo_data_imputation.py#L60-L65

**Comment by mrtrunghieu1** [comment]
I just fixed hard-code problems. Can you review them again?

**Comment by vu-luong** [comment]
Seems like the number of folds (=2) is still hard code. Also, you should assign `fold_size = 2*n_iterations+1` to make `2*n_iterations+1` interpretable.
